language: csharp
dist: xenial
solution: CharacterCustomizer.sln
mono: none
dotnet: 2.2
before_install:
- openssl aes-256-cbc -k "$auth_pass" -in auth.json.enc -out auth.json -d
before_script:
- cd ..
- git clone --depth=50 --branch=master "https://github.com/AsterAether/RiskOfRainDLLs.git"
- git clone --depth=50 --branch=master "https://github.com/AsterAether/AetherLib.git"
- cd AetherLib
- chmod +x AetherLib/after_build.sh
- chmod +x AetherLib/before_build.sh
- dotnet build AetherLib.sln
- cd ../CharacterCustomizer
script:
- chmod +x CharacterCustomizer/after_build.sh
- chmod +x CharacterCustomizer/before_build.sh
- dotnet build
after_success:
  - chmod +x ./deploy.sh
  - ./deploy.sh "${TRAVIS_BRANCH}"
env:
  global:
    secure: AusY+rstgr3z59YUwvjSOh1UyBB5gXvMfZv5eXcdxdngg/8NyxUwRxMABbHfagfRUn1jZdTxssOnIqBUW4uGng+mKrXVctP44vFlzLGc0wLcutP3Wopoib5peAOKXRy9P/QpM9bHSGB45s+H2dFwPhoavEOmCiF926n5+0upLISBanhMSJKUMlRZ4rpU1spNup3ZX8Q+ZwSYBk9GIIA5Ta6zhtYo0qTxemeXcMcF2j8uCoWt3wPRT4XkJftaEkswHmKQ3fuAO6ZxqDlkSjZzxhw0mkDdf3WX/t1ggyANt7E4yXuJm/5fo+L68wHgOY3TL3q78cvRhQUB9hegwx8asjBk8zxkD8zqjGHakii3+CAFAYiuhO+eFrxdGNqxcZvAOljFI1LENKK9HFikgBiRs4sXrsynz8R92rV3vrc3zsJEVvQt9imyVDmSESs/VuQDy4cMBy3M88BASoQlM6FDPM/5P5jnpGG/bdvvC+mz7f+fzqTiadzYFCuycEWXowCZCldyqSlUS86VMdhspuzA+gSj4xEfDQfbA9KiH8600kQ1Kb1zBPzaG+5Cmw0DUqkQ3WPmj+0bNGDnm781L22b1NmTRHRX8+wgqNU0QK9Qpo2Y1KSVNxFA3PteDnWW6chJvbl/hZUjhEYoUNl8qTbhl+JM50Qc1rr2UPnwLjobBMY=
deploy:
  provider: releases
  api_key:
    secure: kdevVJ7aNM3cEmdcX0TfwMpovafOBvCNtHGBaVxglgkVJgyJI705CfTBfeJBhtCUAUkAv+sSKbvT0tD4lcTsfhbHwLDtbqcOsR/Vn5+YLTE/38JmkotrMZPJqINgh7fl4ZwaVnF2KZ5ZyrNpo5wUHnufHpgBpD9QCaJhq71yGM2QCWUIFeJ4hHuV2AjTtu4EDWDDWlXakEF8bu9f+MgoTtyuR/4UB4mb4C2lYwc8txtSE3tqpCGUr+sy6ZJmr4CmZZUPwKZMc3jyCxtJVlZ0LXwcYK7NsArHnySOMSgK71mFmT1MwjdNu6b9sflff1xlalc5L08nR4NlZqBns3zhlOXzDPSRYGKd2ZKNOeHQ0Y6F9wUAcc/Tj01Eknmg+d5rlr0JFrZZfU8prtKmA7ymlhQfpQddynWZQR3oR6MC92D0VKs26GW/0Yrm6Am2M6+AK5D8wuVqWi01JSFeI4B1Fv8sXWuY8wHStx5mQ4ewVg5pYcZ8QuZv7kyFSck9q+GCRysvJeSJ9eEGyQKE/KmGjnqvM8e93AEYagEZ/waGh+Rc4jOP9sAk6JklQnVED6ISnn+kBD7F9sLc46qdjvbzsa9qrcGA+6COTkfim0NWcMue4mi40Pj+ODwb7sYb93ml8YHccf+UxnC6CV3jpQHXRpNpxeXsDmCCMWIJ/MZoKEg=
  file: "./${TRAVIS_BRANCH}.zip"
  skip_cleanup: true
  on:
    tags: true
