language: csharp
dist: xenial
solution: CharacterCustomizer.sln
mono: none
dotnet: 2.2
before_install:
- openssl aes-256-cbc -k "$auth_pass" -in auth.json.enc -out auth.json -d
before_script:
- cd ..
- git clone --depth=50 --branch=master "https://github.com/AsterAether/RiskOfRainDLLs.git"
- git clone --depth=50 --branch=master "https://github.com/AsterAether/AetherLib.git"
- cd AetherLib
- dotnet build AetherLib.sln
- cd ./CharacterCustomizer
script:
- chmod +x CharacterCustomizer/after_build.sh
- dotnet build
- curl -L "https://drive.google.com/uc?id=1Ej8VgsW5RgK66Btb9p74tSdHMH3p4UNb&export=download"
  > gdrive
- ls -al
- chmod +x ./gdrive
- mv ./CharacterCustomizer/build/build.zip "./${TRAVIS_BRANCH}-build-${TRAVIS_BUILD_NUMBER}.zip"
- ./gdrive -c . --service-account auth.json upload -p 1l1JiFC6RP8Z6NHly-8yUilUjzPNXEiiR
  "./${TRAVIS_BRANCH}-build-${TRAVIS_BUILD_NUMBER}.zip"
env:
  global:
    secure: eQfko/jzGIAJH9FcDQwWQxIdVatwCiWUoqK/lckiAgqREt01ZB9hbDmLSjabdNdAXya+HqZ6UkzciTUc+sr5+Bcg6+INY26ewuUK5+L+neCUl01V7pbJm7qu5LZmrUVV92N6INZz+TEabf1VpinTr6ZSW0J/cv0Zo9UJiWuyIZSz8Hvj0qnyP8Ai3SxW0HEJKjeaoqHiEBLZOk4w4t31+rBuzOPSQRe4V48Fqbiy6IW/lFMAt7DZtWC40x+qFmVgHdoCifBSN7w7/wdto5Wp6inBlum1LcF8mLR8QS5aJbIzStwOCgkFrH7QTaVldDc2EqoIVE+dvgYhzQi115LAAqU0XR+HLLVT5A9SHY+zmeIO+aUHM9+mWOYbQ0Hr3pd+fC9BcMHzMYHJhz6xoa6WY63mXyDLEXMD+wqfZmy36kEA4LQjIV1AE6fx21t16+mgQJ7AE8dqqYNjtp6u/ihgXMJRbBpQtmzre+5SZG8dhf8tsTy95CukwG6Hq0D1k18BhGT88H/KGPsKmU4GbUZ3ObV1o7YHqhBeNcfOhT1JEir9kCwebcEhKsRwUwfDdxghzS9shsGJzLGPb3AolXTJH1uUsi5Arl3hL9Ur5OlIYNz1gsAf3Qjk3Jp6xC0uQiQq+lTGhf86/5xnSdvMvstG6bN/Br1zpe9mzkt7hyJNf8k=
