language: csharp
dist: xenial
solution: CharacterCustomizer.sln
mono: none
dotnet: 2.2
before_install:
- openssl aes-256-cbc -k "$auth_pass" -in auth.json.enc -out auth.json -d
before_script:
- cd ..
- git clone --depth=50 --branch=master "https://github.com/AsterAether/RiskOfRainDLLs.git"
- git clone --depth=50 --branch=master "https://github.com/AsterAether/AetherLib.git"
- cd AetherLib
- dotnet build AetherLib.sln
- cd ./CharacterCustomizer
script:
- chmod +x CharacterCustomizer/after_build.sh
- dotnet build
- curl -L "https://drive.google.com/uc?id=1Ej8VgsW5RgK66Btb9p74tSdHMH3p4UNb&export=download" > gdrive
- ls -al
- chmod +x ./gdrive
- mv ./CharacterCustomizer/build/build.zip "./${TRAVIS_BRANCH}-build-${TRAVIS_BUILD_NUMBER}.zip"
- ./gdrive -c . --service-account auth.json upload -p 1l1JiFC6RP8Z6NHly-8yUilUjzPNXEiiR "./${TRAVIS_BRANCH}-build-${TRAVIS_BUILD_NUMBER}.zip"
env:
  global:
    secure: L+SzzS2KyL47PId0Z3I5OL/+sHVQy5kF4YDMJmU+cDWzzpLK1x1DK2ADlHdxxLjxOPI0vFETEVf/cNRpq8NLoWMGeRM6rGVa9oXIqadHMCHGozAvwlQKb7qPDQKSyWmTx2220fnE3fGALuoQjkup++JCrDtVluCcdm1BMQ55dDAmLwiwqfHAbekOSB6fVLHFanZWicvANIQiqbmhE2/Y/YaWl+vdyvf3pJsWOn1wbQ5g32KC2UcLrCetrwWVTk0660WfbteITt7srmvsR+OG8lkTSB84W7LUACVdZDYU2BGysJO0BqJbRZC4os5+Ez4TPHckT62L4yBpbDm/4NH/d/Z2EIBDk8ZarASyShLuDhTc9M1lY+oIN1LNkjffLlpiSNKJSEEcd78ajJcWIQyFexbH2VGn9Me70PspQsyynF1KU7wEi/rnk1vYDULgAYx4Pw6zW9RgPk2cUwCxmV4gcNEZgA/mWT0S/Nl5p3StgCX7Tulfurrw9HPvuxdos0PFRzeF0DLvj+sKEPOnTFC1hwwHlMhPogNatk6ro0g9qQvN55ls9us7SicATH7JdKe/HMx4m55ThOvXJa6OE6YcG4LiWy8ElieSq2nSoGgU1gnASZV5KeunrNE9uZWD956ts+3gxPHGJA/1D23eWfbJ/yA07AMPmlKr3AlD++UuqXw=
